# Generated by Django 3.2.13 on 2022-05-21 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='CREATE_DATE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departments',
            name='update_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='UPDATE_DATE'),
        ),
        migrations.AddField(
            model_name='employees',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='CREATE_DATE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='update_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='UPDATE_DATE'),
        ),
    ]
