version: '3.7'

services:
  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:9.6.24 # latest
    restart: always
    # networks:
    #   netgroup:
    #     ipv4_address: 172.18.0.14
    ports:
    - "5432:5432"
    privileged: true
    volumes:
      # Just specify a path and let the Engine create a volume
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    privileged: true
    cap_add:
      - NET_ADMIN
    env_file:
      - postgres.env
    deploy:
      resources:
        limits:
          memory: 2g
# networks:
#   netgroup:
#     name: netgroup
#     driver: bridge
#     attachable: true
#     ipam:
#       config:
#         - subnet: 172.18.0.0/16
#           gateway: 172.18.0.1
